// ─── Trade Skills Assessment — Question Bank ────────────────────────────────

export interface QuizQuestion {
  id: string;
  category: string;
  question: string;
  options: string[];
  correctIndex: number;
  difficulty: "basic" | "intermediate" | "advanced";
  explanation: string;
}

// ─── Plumbing ────────────────────────────────────────────────────────────────

const plumbingQuestions: QuizQuestion[] = [
  {
    id: "plumb-001",
    category: "plumbing",
    question: "What is the minimum slope per foot required for a 4-inch horizontal drain pipe per the IPC?",
    options: ["1/16 inch per foot", "1/8 inch per foot", "1/4 inch per foot", "1/2 inch per foot"],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "The IPC requires a minimum slope of 1/8 inch per foot for pipes 4 inches and larger. Pipes 3 inches and smaller require 1/4 inch per foot.",
  },
  {
    id: "plumb-002",
    category: "plumbing",
    question: "What is the maximum distance a P-trap can be from the fixture it serves?",
    options: ["12 inches", "24 inches", "30 inches", "48 inches"],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "Per most plumbing codes, the trap arm (distance from trap weir to vent) must not exceed 30 inches for a 1-1/2 inch trap arm. This prevents siphonage of the trap seal.",
  },
  {
    id: "plumb-003",
    category: "plumbing",
    question: "What size water supply line is typically required for a residential water heater?",
    options: ["1/2 inch", "3/4 inch", "1 inch", "1-1/4 inch"],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "A 3/4-inch supply line is the standard requirement for residential water heaters to ensure adequate flow and pressure.",
  },
  {
    id: "plumb-004",
    category: "plumbing",
    question: "What is the purpose of a backflow preventer in a plumbing system?",
    options: [
      "To increase water pressure",
      "To prevent contaminated water from flowing back into the potable supply",
      "To filter sediment from the water",
      "To regulate water temperature",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "A backflow preventer protects the potable water supply from contamination by preventing reverse flow. Required at all cross-connection points.",
  },
  {
    id: "plumb-005",
    category: "plumbing",
    question: "When soldering copper pipe, what temperature should the torch reach to properly melt lead-free solder?",
    options: ["200-300\u00B0F", "350-450\u00B0F", "450-550\u00B0F", "600-700\u00B0F"],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "Lead-free solder melts at approximately 450-550\u00B0F. The copper must be heated enough to draw the solder into the joint by capillary action.",
  },
  {
    id: "plumb-006",
    category: "plumbing",
    question: "What is the minimum trap seal depth required by the IPC for most fixtures?",
    options: ["1 inch", "2 inches", "3 inches", "4 inches"],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "The IPC requires a minimum 2-inch water seal in traps. This prevents sewer gases from entering the building through the drain system.",
  },
  {
    id: "plumb-007",
    category: "plumbing",
    question: "What is the maximum water temperature setting recommended for residential water heaters to prevent scalding?",
    options: ["100\u00B0F", "110\u00B0F", "120\u00B0F", "140\u00B0F"],
    correctIndex: 2,
    difficulty: "basic",
    explanation: "120\u00B0F is the recommended maximum setting. At 140\u00B0F, scalding can occur in just 5 seconds. Anti-scald mixing valves are recommended for additional safety.",
  },
  {
    id: "plumb-008",
    category: "plumbing",
    question: "What type of fitting is required when transitioning from ABS to PVC drain pipe?",
    options: [
      "A rubber coupling with band clamps",
      "Direct solvent-weld with PVC cement",
      "A mechanical no-hub coupling or approved transition cement",
      "A threaded adapter fitting",
    ],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "ABS and PVC cannot be directly solvent-welded together with standard cement. An approved transition cement or mechanical coupling (no-hub, banded, etc.) is required.",
  },
  {
    id: "plumb-009",
    category: "plumbing",
    question: "What is the purpose of a hammer arrestor in a plumbing system?",
    options: [
      "To remove air from the lines",
      "To absorb the shock wave when a valve closes quickly (water hammer)",
      "To increase water pressure at fixtures",
      "To prevent backflow at hose bibs",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "Water hammer arrestors contain a sealed air chamber or piston that absorbs the pressure spike when fast-closing valves (like washing machine solenoids) shut off suddenly.",
  },
  {
    id: "plumb-010",
    category: "plumbing",
    question: "What is the minimum size vent pipe that can serve a toilet (water closet)?",
    options: ["1-1/4 inch", "1-1/2 inch", "2 inch", "3 inch"],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "A 2-inch vent is the minimum required for a water closet. The vent must be sized based on the fixture unit load and the developed length of the vent.",
  },
];

// ─── Electrical ──────────────────────────────────────────────────────────────

const electricalQuestions: QuizQuestion[] = [
  {
    id: "elec-001",
    category: "electrical",
    question: "Per the NEC, what is the maximum number of #12 AWG THHN conductors allowed in a 3/4-inch EMT conduit?",
    options: ["6", "9", "12", "16"],
    correctIndex: 3,
    difficulty: "intermediate",
    explanation: "Per NEC Chapter 9 Table 1 and Annex C, a 3/4-inch EMT can hold up to 16 #12 THHN conductors at 40% fill capacity.",
  },
  {
    id: "elec-002",
    category: "electrical",
    question: "GFCI protection is required in which of the following residential locations?",
    options: [
      "All bedroom receptacles",
      "Bathrooms, kitchens (within 6 feet of sink), garages, and outdoor receptacles",
      "Only outdoor receptacles",
      "Any receptacle within 10 feet of a water source",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "NEC 210.8 requires GFCI protection in bathrooms, garages, outdoors, crawl spaces, unfinished basements, kitchen countertop receptacles, laundry areas, and within 6 feet of sinks.",
  },
  {
    id: "elec-003",
    category: "electrical",
    question: "What is the ampacity of #10 AWG copper THHN wire at 30\u00B0C ambient temperature?",
    options: ["20 amps", "30 amps", "35 amps", "40 amps"],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "Per NEC Table 310.16, #10 AWG THHN (90\u00B0C column) is rated for 40A, but after applying the 75\u00B0C termination temperature limitation, the usable ampacity is 35A.",
  },
  {
    id: "elec-004",
    category: "electrical",
    question: "What is the standard voltage drop recommendation for branch circuits per the NEC?",
    options: ["1%", "3%", "5%", "10%"],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "NEC 210.19(A) Informational Note recommends no more than 3% voltage drop on branch circuits, and no more than 5% total (feeder + branch circuit combined).",
  },
  {
    id: "elec-005",
    category: "electrical",
    question: "What is the maximum overcurrent protection for a #14 AWG copper conductor?",
    options: ["10 amps", "15 amps", "20 amps", "25 amps"],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "NEC 240.4(D) limits #14 AWG copper to 15-amp overcurrent protection. This cannot be increased regardless of the insulation temperature rating.",
  },
  {
    id: "elec-006",
    category: "electrical",
    question: "When is arc-fault circuit interrupter (AFCI) protection required in a dwelling?",
    options: [
      "Only in bedrooms",
      "Kitchens, family rooms, dining rooms, living rooms, parlors, libraries, dens, bedrooms, sunrooms, recreation rooms, closets, hallways, laundry areas, and similar rooms",
      "Only in rooms with carpet",
      "AFCI is optional in all residential applications",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "NEC 210.12(A) requires AFCI protection for virtually all 120V, 15A and 20A branch circuits in dwelling units, covering nearly every living space.",
  },
  {
    id: "elec-007",
    category: "electrical",
    question: "What is the minimum burial depth for UF (underground feeder) cable without additional protection?",
    options: ["6 inches", "12 inches", "18 inches", "24 inches"],
    correctIndex: 3,
    difficulty: "intermediate",
    explanation: "NEC Table 300.5 requires a minimum cover of 24 inches for direct-buried UF cable. In rigid conduit, the depth can be reduced to 18 inches.",
  },
  {
    id: "elec-008",
    category: "electrical",
    question: "What is the NEC requirement for the minimum number of receptacle outlets in a dwelling unit kitchen?",
    options: [
      "One receptacle per counter section",
      "Two 20-amp small-appliance branch circuits serving the kitchen countertop area",
      "One dedicated 20-amp circuit for the kitchen",
      "GFCI receptacles every 4 feet along the countertop",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "NEC 210.11(C)(1) requires a minimum of two 20-amp small-appliance branch circuits to serve the kitchen, pantry, breakfast room, and dining room counter receptacles.",
  },
  {
    id: "elec-009",
    category: "electrical",
    question: "What wire gauge is required for a 40-amp, 240-volt electric range circuit?",
    options: ["#10 AWG", "#8 AWG", "#6 AWG", "#4 AWG"],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "A 40-amp circuit requires #8 AWG copper conductors (NEC 240.4(D) and Table 310.16). The circuit also requires a 40-amp breaker and appropriate receptacle.",
  },
  {
    id: "elec-010",
    category: "electrical",
    question: "What is the maximum height above the floor for a residential electrical panel?",
    options: [
      "5 feet 6 inches to the top",
      "6 feet 7 inches to the center of the top breaker handle",
      "7 feet to the top of the panel",
      "No maximum, only a minimum of 4 feet",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "NEC 240.24(A) and 404.8(A) require that circuit breaker handles in their highest position be no more than 6 feet 7 inches above the floor or working platform.",
  },
];

// ─── HVAC ────────────────────────────────────────────────────────────────────

const hvacQuestions: QuizQuestion[] = [
  {
    id: "hvac-001",
    category: "hvac",
    question: "What EPA certification is required to purchase and handle refrigerants?",
    options: [
      "EPA Section 608 certification",
      "OSHA 30-hour certification",
      "NATE certification",
      "No certification is required",
    ],
    correctIndex: 0,
    difficulty: "basic",
    explanation: "EPA Section 608 certification is mandatory for anyone who purchases, handles, or recovers refrigerants. There are four types (I, II, III, and Universal) based on the equipment serviced.",
  },
  {
    id: "hvac-002",
    category: "hvac",
    question: "What is the standard residential duct velocity for a main trunk line in a low-velocity system?",
    options: ["200-400 FPM", "600-900 FPM", "1000-1200 FPM", "1500-2000 FPM"],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "Main trunk lines in residential systems typically operate at 600-900 FPM. Higher velocities cause noise issues, while lower velocities require oversized ductwork.",
  },
  {
    id: "hvac-003",
    category: "hvac",
    question: "What does SEER stand for, and what is the current federal minimum for residential split-system AC units (as of 2023)?",
    options: [
      "Seasonal Energy Efficiency Ratio; 13 SEER",
      "Standard Equipment Efficiency Rating; 14 SEER",
      "Seasonal Energy Efficiency Ratio; 14-15 SEER2 (varies by region)",
      "System Energy Expenditure Ratio; 16 SEER",
    ],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "SEER is Seasonal Energy Efficiency Ratio. As of January 2023, the DOE requires 14 SEER2 in the northern region and 15 SEER2 in the southern region for residential split systems.",
  },
  {
    id: "hvac-004",
    category: "hvac",
    question: "What is the proper superheat range for a properly charged TXV (thermostatic expansion valve) system?",
    options: ["0-5\u00B0F", "8-14\u00B0F", "20-30\u00B0F", "35-45\u00B0F"],
    correctIndex: 1,
    difficulty: "advanced",
    explanation: "A TXV system should have 8-14\u00B0F of superheat at the evaporator. The TXV regulates flow to maintain this range regardless of load conditions.",
  },
  {
    id: "hvac-005",
    category: "hvac",
    question: "When recovering refrigerant, what is the required recovery level for a system containing more than 200 lbs of R-410A?",
    options: [
      "80% of the charge",
      "90% of the charge",
      "0 PSIG",
      "Recovery to specific vacuum levels per EPA regulations",
    ],
    correctIndex: 3,
    difficulty: "advanced",
    explanation: "EPA regulations require recovery to specific vacuum levels based on the type of equipment and refrigerant type, not a percentage. For high-pressure systems over 200 lbs, recovery must reach 0 PSIG.",
  },
  {
    id: "hvac-006",
    category: "hvac",
    question: "What is the general rule of thumb for residential cooling load estimation?",
    options: [
      "200 sq ft per ton of cooling",
      "400-600 sq ft per ton of cooling",
      "800-1000 sq ft per ton of cooling",
      "1200 sq ft per ton of cooling",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "A rough estimate is 400-600 sq ft per ton, though a proper Manual J load calculation should always be performed. Climate, insulation, windows, and other factors greatly affect the actual load.",
  },
  {
    id: "hvac-007",
    category: "hvac",
    question: "What is the maximum refrigerant line set length typically recommended for a mini-split system?",
    options: ["25 feet", "50 feet", "75-100 feet", "200 feet"],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "Most mini-split manufacturers allow 75-100 feet of line set, though some allow up to 164 feet with additional charge. Additional refrigerant must be added beyond the factory pre-charge length.",
  },
  {
    id: "hvac-008",
    category: "hvac",
    question: "What is the proper subcooling range for a system with a TXV metering device?",
    options: ["5-10\u00B0F", "10-15\u00B0F", "20-25\u00B0F", "0\u00B0F (saturated liquid)"],
    correctIndex: 1,
    difficulty: "advanced",
    explanation: "Proper subcooling for a TXV system is typically 10-15\u00B0F (check manufacturer specifications). Subcooling is the primary method for checking charge on TXV systems.",
  },
  {
    id: "plumb-hvac-009",
    category: "hvac",
    question: "What is the purpose of a condensate trap on a high-efficiency furnace?",
    options: [
      "To collect dust and debris",
      "To prevent flue gases from escaping through the condensate drain",
      "To regulate gas pressure",
      "To increase system efficiency",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "The condensate trap maintains a water seal to prevent combustion gases from venting through the condensate drain line. A high-efficiency furnace operates under positive pressure in the vent.",
  },
  {
    id: "hvac-010",
    category: "hvac",
    question: "What type of refrigerant is R-410A classified as?",
    options: [
      "CFC (chlorofluorocarbon)",
      "HCFC (hydrochlorofluorocarbon)",
      "HFC (hydrofluorocarbon) — a near-azeotropic blend",
      "Natural refrigerant",
    ],
    correctIndex: 2,
    difficulty: "basic",
    explanation: "R-410A is an HFC (hydrofluorocarbon) that is a near-azeotropic blend of R-32 and R-125. It has zero ozone depletion potential but high GWP. It must be charged as a liquid, not vapor.",
  },
];

// ─── General Contracting ─────────────────────────────────────────────────────

const generalContractingQuestions: QuizQuestion[] = [
  {
    id: "gc-001",
    category: "general_contracting",
    question: "When is a building permit typically required for residential work?",
    options: [
      "Only for new construction",
      "For structural changes, electrical, plumbing, and HVAC work that changes the system",
      "Only when the project cost exceeds $10,000",
      "Permits are only required for commercial buildings",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Permits are generally required for any structural work, changes to electrical/plumbing/HVAC systems, additions, and significant remodels. Minor cosmetic work (paint, flooring, fixtures) usually does not require a permit.",
  },
  {
    id: "gc-002",
    category: "general_contracting",
    question: "What is the primary purpose of a load-bearing wall?",
    options: [
      "To divide rooms for privacy",
      "To transfer structural loads from above to the foundation",
      "To house electrical and plumbing runs",
      "To provide fire separation between rooms",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Load-bearing walls transfer the weight of the roof, floors, and upper stories down to the foundation. Removing them without proper engineering (beam, header, post) can cause structural failure.",
  },
  {
    id: "gc-003",
    category: "general_contracting",
    question: "What does the critical path represent in project management?",
    options: [
      "The most expensive sequence of tasks",
      "The longest sequence of dependent tasks that determines the minimum project duration",
      "The path inspectors take through the building",
      "The order in which permits must be obtained",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "The critical path is the longest chain of dependent activities. Any delay on a critical path task directly delays the project completion date. It is the key focus for schedule management.",
  },
  {
    id: "gc-004",
    category: "general_contracting",
    question: "What is the minimum footing depth below grade in areas with frost?",
    options: [
      "6 inches",
      "12 inches",
      "Below the local frost line depth",
      "24 inches in all climates",
    ],
    correctIndex: 2,
    difficulty: "basic",
    explanation: "Footings must extend below the local frost line to prevent frost heave. Frost depth varies by region (12 inches in the south to 60+ inches in northern states). Local building codes specify the required depth.",
  },
  {
    id: "gc-005",
    category: "general_contracting",
    question: "What is the maximum span for a standard 2x10 floor joist at 16 inches on-center using #2 grade SPF (Spruce-Pine-Fir) lumber?",
    options: [
      "8 feet",
      "12 feet",
      "15-16 feet",
      "20 feet",
    ],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "A #2 SPF 2x10 at 16-inch OC can span approximately 15-16 feet for a 40 PSF live load. Actual span depends on species, grade, spacing, and load requirements per IRC span tables.",
  },
  {
    id: "gc-006",
    category: "general_contracting",
    question: "What is the purpose of a vapor barrier in construction?",
    options: [
      "To prevent air movement through walls",
      "To control moisture migration through building assemblies",
      "To provide insulation value",
      "To block sound transmission",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "A vapor barrier (or vapor retarder) controls moisture diffusion through walls, ceilings, and floors. Proper placement depends on climate zone \u2014 warm side of insulation in cold climates.",
  },
  {
    id: "gc-007",
    category: "general_contracting",
    question: "What is the IRC requirement for residential stair riser height?",
    options: [
      "Maximum 6 inches",
      "Maximum 7-3/4 inches",
      "Exactly 8 inches",
      "No specific requirement, just uniform height",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "IRC R311.7.5.1 limits residential stair risers to a maximum of 7-3/4 inches. The greatest riser height within a flight cannot exceed the smallest by more than 3/8 inch.",
  },
  {
    id: "gc-008",
    category: "general_contracting",
    question: "What type of foundation is best suited for expansive clay soils?",
    options: [
      "Standard slab-on-grade",
      "Pier and beam (post-tensioned slab or drilled piers)",
      "Crawl space with concrete block walls",
      "Shallow strip footings",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "Expansive clay soils require foundations that can accommodate soil movement. Post-tensioned slabs or drilled pier foundations that extend below the active zone are preferred in these conditions.",
  },
  {
    id: "gc-009",
    category: "general_contracting",
    question: "What is the minimum concrete strength (PSI) typically specified for residential footings?",
    options: [
      "1500 PSI",
      "2500 PSI",
      "3000 PSI",
      "4000 PSI",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "IRC Table R402.2 specifies a minimum of 2500 PSI concrete for footings, with higher strengths required in areas with moderate-to-severe weathering potential. Foundation walls typically require 2500-3000 PSI.",
  },
  {
    id: "gc-010",
    category: "general_contracting",
    question: "How do you identify if an interior wall is load-bearing?",
    options: [
      "Load-bearing walls are always thicker than partition walls",
      "Check if it runs perpendicular to floor/ceiling joists and sits above a beam or wall below",
      "Only exterior walls can be load-bearing",
      "Tap the wall \u2014 load-bearing walls sound solid",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "A wall running perpendicular to joists, centered over a beam or bearing wall below, is likely load-bearing. Always verify with structural plans or an engineer before removal.",
  },
];

// ─── Roofing ─────────────────────────────────────────────────────────────────

const roofingQuestions: QuizQuestion[] = [
  {
    id: "roof-001",
    category: "roofing",
    question: "What is the minimum roof slope recommended for standard asphalt shingles?",
    options: ["1:12", "2:12", "4:12", "6:12"],
    correctIndex: 2,
    difficulty: "basic",
    explanation: "Standard asphalt shingles require a minimum 4:12 slope. Slopes between 2:12 and 4:12 require additional underlayment. Below 2:12, shingles should not be used.",
  },
  {
    id: "roof-002",
    category: "roofing",
    question: "What is the primary purpose of roof flashing?",
    options: [
      "To provide additional insulation",
      "To redirect water away from joints, penetrations, and transitions",
      "To hold shingles in place during high winds",
      "To improve the aesthetic appearance of the roof",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Flashing (metal or rubber) directs water away from vulnerable areas where different surfaces meet: chimneys, walls, valleys, vent pipes, and skylights. It is the most common source of leaks when improperly installed.",
  },
  {
    id: "roof-003",
    category: "roofing",
    question: "What is an ice and water shield, and where is it installed?",
    options: [
      "A type of metal flashing installed at the ridge",
      "A self-adhering waterproof membrane installed at eaves, valleys, and penetrations",
      "A heating element installed in gutters",
      "A spray-on coating for the entire roof deck",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Ice and water shield is a self-adhering, rubberized asphalt membrane installed at eaves (at least 24 inches past the exterior wall), valleys, and around penetrations to prevent leaks from ice dams and wind-driven rain.",
  },
  {
    id: "roof-004",
    category: "roofing",
    question: "How many square feet of roof area does one \"square\" of roofing material cover?",
    options: ["10 sq ft", "50 sq ft", "100 sq ft", "200 sq ft"],
    correctIndex: 2,
    difficulty: "basic",
    explanation: "One \"square\" of roofing equals 100 square feet. This is the standard unit of measurement for ordering roofing materials. A typical bundle of 3-tab shingles covers about 33.3 sq ft (3 bundles per square).",
  },
  {
    id: "roof-005",
    category: "roofing",
    question: "What is the standard exposure (reveal) for architectural asphalt shingles?",
    options: ["3 inches", "5 inches", "5-5/8 inches", "7 inches"],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "Most architectural (dimensional) shingles have a 5-5/8 inch exposure, giving them their layered appearance. The exact exposure should follow the manufacturer's installation instructions.",
  },
  {
    id: "roof-006",
    category: "roofing",
    question: "What is the purpose of a ridge vent?",
    options: [
      "To drain water from the ridge",
      "To provide exhaust ventilation at the highest point of the roof",
      "To reinforce the ridge against wind uplift",
      "To prevent birds from nesting under shingles",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Ridge vents allow hot, moist air to exhaust from the attic at the highest point. Combined with soffit intake vents, they create continuous airflow that prevents moisture buildup and ice dams.",
  },
  {
    id: "roof-007",
    category: "roofing",
    question: "What is the IRC requirement for attic ventilation ratio?",
    options: [
      "1:100 (1 sq ft of vent per 100 sq ft of attic floor)",
      "1:150 (with balanced intake/exhaust)",
      "1:300 (with balanced intake/exhaust)",
      "No specific ratio is required",
    ],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "IRC R806.2 requires a minimum ventilation ratio of 1:150, which can be reduced to 1:300 when ventilation is balanced between upper (exhaust) and lower (intake) vents, with 50-80% at the eave/soffit.",
  },
  {
    id: "roof-008",
    category: "roofing",
    question: "When installing a new roof over an existing layer, what is the maximum number of roofing layers allowed by most codes?",
    options: ["1 (no overlay allowed)", "2 layers total", "3 layers total", "No limit if structurally sound"],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Most building codes allow a maximum of 2 layers of asphalt shingles. Beyond this, a complete tear-off is required. Weight, bonding issues, and inability to inspect the deck are key concerns.",
  },
  {
    id: "roof-009",
    category: "roofing",
    question: "What nail length is recommended for attaching asphalt shingles to a new roof deck?",
    options: ["3/4 inch", "1 inch", "1-1/4 inches", "2 inches"],
    correctIndex: 2,
    difficulty: "intermediate",
    explanation: "Nails should be 1-1/4 inches long for new construction (to penetrate through the shingle and at least 3/4 inch into the deck). Longer nails (1-3/4 inch) are needed for re-roof over existing shingles.",
  },
  {
    id: "roof-010",
    category: "roofing",
    question: "What is a drip edge and where is it installed?",
    options: [
      "A rubber strip under shingles at valleys",
      "An L-shaped metal flashing installed at the eave and rake edges of the roof",
      "A gutter attachment accessory",
      "A ridge cap shingle",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Drip edge is an L-shaped metal flashing that directs water away from the fascia and into the gutter. It is installed at eaves (under the underlayment) and rakes (over the underlayment).",
  },
];

// ─── Auto Repair ─────────────────────────────────────────────────────────────

const autoRepairQuestions: QuizQuestion[] = [
  {
    id: "auto-001",
    category: "auto_repair",
    question: "What does OBD-II code P0300 indicate?",
    options: [
      "Oxygen sensor malfunction",
      "Random/multiple cylinder misfire detected",
      "Catalytic converter efficiency below threshold",
      "Mass airflow sensor circuit malfunction",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "P0300 indicates random/multiple cylinder misfires. Codes P0301-P0312 indicate specific cylinder misfires. Common causes include bad spark plugs, ignition coils, fuel injectors, or vacuum leaks.",
  },
  {
    id: "auto-002",
    category: "auto_repair",
    question: "What is the minimum brake pad thickness before replacement is recommended?",
    options: ["1/8 inch (3mm)", "1/4 inch (6mm)", "1/2 inch (12mm)", "3/4 inch (19mm)"],
    correctIndex: 0,
    difficulty: "basic",
    explanation: "Brake pads should be replaced when they reach 3mm (1/8 inch) or less. Most new pads start at 10-12mm. Many vehicles have wear indicators that squeal at approximately 2-3mm.",
  },
  {
    id: "auto-003",
    category: "auto_repair",
    question: "What component controls ignition timing in a modern fuel-injected engine?",
    options: [
      "Distributor and vacuum advance",
      "The ECM/PCM using inputs from the crankshaft position sensor and other sensors",
      "The ignition coil directly",
      "The throttle position sensor",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Modern engines use the ECM/PCM to calculate ignition timing based on crankshaft position, engine load, temperature, knock sensor input, and other parameters. Distributors are obsolete in modern systems.",
  },
  {
    id: "auto-004",
    category: "auto_repair",
    question: "What is the correct torque specification for most standard lug nuts on passenger vehicles?",
    options: ["50-60 ft-lbs", "80-100 ft-lbs", "120-150 ft-lbs", "200+ ft-lbs"],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Most passenger vehicles require 80-100 ft-lbs for lug nuts (check specific vehicle specs). Always use a torque wrench. Over-torquing can warp rotors and strip threads; under-torquing risks wheel loss.",
  },
  {
    id: "auto-005",
    category: "auto_repair",
    question: "What does a fuel trim reading of +25% (Long Term Fuel Trim) typically indicate?",
    options: [
      "The engine is running rich and the ECM is removing fuel",
      "The engine is running lean and the ECM is adding extra fuel to compensate",
      "The fuel system is operating normally",
      "The catalytic converter is failing",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "A positive LTFT of +25% means the ECM is adding 25% more fuel than the base map to maintain stoichiometric ratio. This typically indicates a vacuum leak, weak fuel pump, or dirty injectors causing a lean condition.",
  },
  {
    id: "auto-006",
    category: "auto_repair",
    question: "What is the standard service interval for replacing engine coolant (conventional green coolant)?",
    options: [
      "Every oil change",
      "Every 2 years or 30,000 miles",
      "Every 5 years or 100,000 miles",
      "Coolant never needs replacement",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "Conventional (green) coolant should be replaced every 2 years or 30,000 miles. Extended-life (OAT/HOAT) coolants can last 5 years or 100,000 miles. Always follow manufacturer specifications.",
  },
  {
    id: "auto-007",
    category: "auto_repair",
    question: "What does a Mode $06 OBD-II test result show?",
    options: [
      "Freeze frame data from the last DTC",
      "Real-time sensor data (PIDs)",
      "Results of on-board monitoring system tests with pass/fail thresholds",
      "Vehicle identification information",
    ],
    correctIndex: 2,
    difficulty: "advanced",
    explanation: "Mode $06 shows the actual test results and thresholds from continuous and non-continuous monitor tests. This data can reveal failing components before a DTC sets, helping diagnose intermittent issues.",
  },
  {
    id: "auto-008",
    category: "auto_repair",
    question: "What is the correct way to check for a parasitic battery drain?",
    options: [
      "Measure voltage at the battery terminals with the engine running",
      "Connect an ammeter in series with the negative battery cable with all doors closed and modules asleep",
      "Measure resistance between the battery terminals",
      "Check the alternator output voltage",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "Parasitic draw is measured with an ammeter in series with the negative cable after all modules have entered sleep mode (typically 30-60 minutes). Normal draw is 20-50mA. Above 75-100mA indicates a problem.",
  },
  {
    id: "auto-009",
    category: "auto_repair",
    question: "What is the purpose of the EVAP system in a modern vehicle?",
    options: [
      "To cool the engine",
      "To capture and recirculate fuel vapors to prevent them from escaping to the atmosphere",
      "To manage exhaust emissions",
      "To regulate cabin air temperature",
    ],
    correctIndex: 1,
    difficulty: "basic",
    explanation: "The EVAP (Evaporative Emission Control) system captures fuel vapors from the fuel tank and canister, then purges them into the intake manifold to be burned during normal engine operation.",
  },
  {
    id: "auto-010",
    category: "auto_repair",
    question: "When performing a compression test, what is considered acceptable variation between cylinders?",
    options: [
      "No more than 5%",
      "No more than 10%",
      "No more than 20%",
      "Any variation is acceptable if all cylinders are above 100 PSI",
    ],
    correctIndex: 1,
    difficulty: "intermediate",
    explanation: "Cylinder compression should not vary more than 10% between the highest and lowest readings. A greater variance indicates worn rings, valves, or head gasket issues in the low cylinder(s).",
  },
];

// ─── Combine all questions ──────────────────────────────────────────────────

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  ...plumbingQuestions,
  ...electricalQuestions,
  ...hvacQuestions,
  ...generalContractingQuestions,
  ...roofingQuestions,
  ...autoRepairQuestions,
];

// Category mapping for display names
export const QUIZ_CATEGORIES: Record<string, string> = {
  plumbing: "Plumbing",
  electrical: "Electrical",
  hvac: "HVAC",
  general_contracting: "General Contracting",
  roofing: "Roofing",
  auto_repair: "Auto Repair",
};

export function getQuestionsForCategory(category: string): QuizQuestion[] {
  return QUIZ_QUESTIONS.filter((q) => q.category === category);
}

export function getRandomQuestions(category: string, count: number = 10): QuizQuestion[] {
  const pool = getQuestionsForCategory(category);
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, pool.length));
}
